version: '3'

services:
  alpha-api:
    image: alpha-api:latest
    container_name: alpha-api
    user: alpha
    environment:
      - TZ=Asia/Seoul
    networks:
      - alpha

networks:
  alpha:
    driver: bridge
