server:
  port: 11122
  tomcat:
    threads:
      max: 200
      min-spare: 10
      
      
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  data:
    jdbc:
      repositories:
        enabled: false
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
alpha:
  sens:
    svc_id: "ncp:sms:kr:258742391636:alpha_sms"
    host: "https://sens.apigw.ntruss.com"
    url: "/sms/v2/services/"
    type: "/messages"
    accessKey: "pSuxFzS1tdb81FrrrCyx"
    secretKey: "iPzyFEUdCsDFTI2JqLBV9IlvUMDLPiUnIL8MnClY"
    message:
      type: "SMS"
      content_type: "COMM"
      country_code: "82"
      message: "[Keep it %s]\n인증번호 [%s] 를 입력해주세요."
      expireTime: 180000
      
jwt:
  accessToken:
    #단위 : 분
    validTime: 20000
  refreshToken:
    validTime: 30000
  secret: a2ltamFlanVuZ3Rlc3RzZWNyZXRza2V5MDEwNTA2NDE0MDZraW1qYWVqdW5ndGVzdHNlY3JldHNrZXkwMTA1MDY0MTQwNmtpbWphZWp1bmd0ZXN0c2VjcmV0c2tleTAxMDUwNjQxNDA2a2ltamFlanVuZ3Rlc3RzZWNyZXRza2V5MDEwNTA2NDE0MDY=
#  secret: kimjaejungtestsecretskey01050641406  * 4

aws:
  accessKey: AKIATZTFTRIS2EU4PKMQ
  secretKey: 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
  S3:
    region: ap-northeast-2
    bucket: keep-it-s3
    
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
