server:
  port: 8080

spring:
  # Set the master node of the PCI-AD Database as the primary database for ATP Project to handle the "CUD" for it.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://keep-it-db.ckmboza0c4mv.ap-northeast-2.rds.amazonaws.com:3306/alpha?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: alpha
    password: alpha#!12
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      generate-ddl: true
      format_sql: true
      generate_statistics: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbitmq:
    host: b-adbf0baf-496f-4415-a7dd-25d528875f82.mq.ap-northeast-2.amazonaws.com
    port: 5671
    username: alpha
    password: alpha#!12
    ssl:
      enabled: true
